import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'login', loadComponent: () => import('./pages/login/login').then((m) => m.Login) },
  { path: 'home', loadComponent: () => import('./pages/home/home').then((m) => m.Home) },
  { path: 'jogador', loadComponent: () => import('./pages/jogador-pages/jogador/jogador').then((m) => m.Jogador) },
  { path: 'cadastro-jogador', loadComponent: () => import('./pages/jogador-pages/cadastro-jogador/cadastro-jogador').then((m) => m.CadastroJogador) },
  { path: 'edicao-jogador', loadComponent: () => import('./pages/jogador-pages/edicao-jogador/edicao-jogador').then((m) => m.EdicaoJogador) },
  { path: 'cadastro-item-catalogo', loadComponent: () => import('./pages/catalogo-pages/cadastro-item-catalogo/cadastro-item-catalogo').then((m) => m.CadastroItemCatalogo) },
  { path: 'cadastro-item-catalogo/:id', loadComponent: () => import('./pages/catalogo-pages/cadastro-item-catalogo/cadastro-item-catalogo').then((m) => m.CadastroItemCatalogo) },
  { path: 'inventario-jogador', loadComponent: () => import('./pages/inventario-pages/inventario-jogador/inventario-jogador').then((m) => m.InventarioJogador) },
  { path: 'item-inventario/:id', loadComponent: () => import('./pages/inventario-pages/item-inventario/item-inventario').then((m) => m.ItemInventario) },
  { path: 'cadastro-inventario', loadComponent: () => import('./pages/inventario-pages/cadastro-inventario/cadastro-inventario').then((m) => m.CadastroInventario) },
  { path: 'cadastro-inventario/:id', loadComponent: () => import('./pages/inventario-pages/cadastro-inventario/cadastro-inventario').then((m) => m.CadastroInventario) },
  { path: 'cadastro-npc', loadComponent: () => import('./pages/npcs-pages/cadastro-npc/cadastro-npc').then((m) => m.CadastroNpc) },
  { path: 'cadastro-npc/:id', loadComponent: () => import('./pages/npcs-pages/cadastro-npc/cadastro-npc').then((m) => m.CadastroNpc) },
  { path: 'npcs', loadComponent: () => import('./pages/npcs-pages/npcs/npcs').then((m) => m.Npcs) },
  { path: 'npc-detalhes', loadComponent: () => import('./pages/npcs-pages/npc-detalhes/npc-detalhes').then((m) => m.NpcDetalhes) },
  { path: 'npc-detalhes/:id', loadComponent: () => import('./pages/npcs-pages/npc-detalhes/npc-detalhes').then((m) => m.NpcDetalhes) },
  { path: 'batalha', loadComponent: () => import('./pages/batalha-pages/batalha/batalha').then((m) => m.Batalha) },
  { path: 'jogador-detalhes-batalha', loadComponent: () => import('./pages/batalha-pages/jogador-detalhes-batalha/jogador-detalhes-batalha').then((m) => m.JogadorDetalhesBatalha) },
  { path: 'jogador-detalhes-batalha/:id', loadComponent: () => import('./pages/batalha-pages/jogador-detalhes-batalha/jogador-detalhes-batalha').then((m) => m.JogadorDetalhesBatalha) },
  { path: 'combate', loadComponent: () => import('./pages/batalha-pages/combate/combate').then((m) => m.Combate) },
  { path: 'combate/:id', loadComponent: () => import('./pages/batalha-pages/combate/combate').then((m) => m.Combate) },
  { path: 'catalogo', loadComponent: () => import('./pages/catalogo-pages/catalogo/catalogo').then((m) => m.Catalogo) },
  { path: 'recuperacao', loadComponent: () => import('./pages/batalha-pages/recuperacao/recuperacao').then((m) => m.Recuperacao) },
  { path: 'recuperacao/:id', loadComponent: () => import('./pages/batalha-pages/recuperacao/recuperacao').then((m) => m.Recuperacao) },
  { path: 'anotacoes', loadComponent: () => import('./pages/anotacoes-pages/anotacoes/anotacoes').then((m) => m.Anotacoes) },
  { path: 'criar-anotacao', loadComponent: () => import('./pages/anotacoes-pages/criar-anotacao/criar-anotacao').then((m) => m.CriarAnotacao) },
  { path: 'criar-anotacao/:id', loadComponent: () => import('./pages/anotacoes-pages/criar-anotacao/criar-anotacao').then((m) => m.CriarAnotacao) },
  { path: 'oficina', loadComponent: () => import('./pages/oficina/oficina').then((m) => m.Oficina) },
  { path: 'skills-jogador', loadComponent: () => import('./pages/skilltree-pages/skills-jogador/skills-jogador').then((m) => m.SkillsJogador) },
  { path: 'troca-de-itens', loadComponent: () => import('./pages/troca-de-itens/troca-de-itens').then((m) => m.TrocaDeItens) },
  { path: 'troca-de-itens/:id', loadComponent: () => import('./pages/troca-de-itens/troca-de-itens').then((m) => m.TrocaDeItens) },
  // 🔑 aqui está o ajuste → rota com parâmetro :id
  { path: 'item-catalogo/:id', loadComponent: () => import('./pages/catalogo-pages/item-catalogo/item-catalogo').then((m) => m.ItemCatalogo) },
  { path: 'skilltree', loadComponent: () => import('./pages/skilltree/skilltree/skilltree').then((m) => m.SkillTree) },
  { path: 'skilltree/:id', loadComponent: () => import('./pages/skilltree/skilltree/skilltree').then((m) => m.SkillTree) },
  { path: 'edicao-skilltree', loadComponent: () => import('./pages/skilltree/edicao-skilltree/edicao-skilltree').then((m) => m.EdicaoSkillTree) },
  { path: 'edicao-skilltree/:id', loadComponent: () => import('./pages/skilltree/edicao-skilltree/edicao-skilltree').then((m) => m.EdicaoSkillTree) },
  { path: 'visao-jogadores', loadComponent: () => import('./pages/jogador-pages/visao-jogadores/visao-jogadores').then((m) => m.VisaoJogadores) },
  { path: 'visao-jogadores/:id', loadComponent: () => import('./pages/jogador-pages/visao-jogadores/visao-jogadores').then((m) => m.VisaoJogadores) },
  { path: 'registro', loadComponent: () => import('./pages/registro/registro').then((m) => m.Registro) },
  { path: 'registro/:id', loadComponent: () => import('./pages/registro/registro').then((m) => m.Registro) },

  { path: '**', redirectTo: 'login' }
];
